/**
 * Dish photos generated by scripts/generate-meal-images.mjs (OpenAI
 * gpt-image-1) into public/meals/. The manifest lists what's actually on
 * disk so components render a photo only when one exists.
 */
import generatedIds from "./meal-images.json";

const available = new Set<string>(generatedIds);

export function mealImageSrc(mealId: string | undefined): string | null {
  return mealId && available.has(mealId) ? `/meals/${mealId}.webp` : null;
}
